
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: list-fs-files
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Script to list files in a directory with epoch timstamp and sha256sum
  description: |
   This script uses os.walk on a specified directory, lists the epoch timestamp and
   generates a sha256sum using the sha256 command.
   It tags files which are not accessible by the root user with 'prblmfl' found in
   directories like /proc for instance.
  
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
      
  layout:
    /usr/bin/list-fs-files.py
      bind: $SNAP/list-fs-files/current/snap/list-fs-files.py
    /usr/bin/lfs_files.py
      bind: $SNAP/$SNAP/list-fs-files/current/snap/lfs_files.py
      
  
